#!/bin/bash

# Define start time in milliseconds (the %3N cuts off the microseconds I think)
START=$(date +%s%3N)

# The network home directory
NET_HOME="/cs/home/$USER"

mkdir -p "$NET_HOME/dotfiles"
pushd "$NET_HOME/dotfiles"
echo Fetching latest version...
git reset --hard HEAD
git pull

echo Adding symlinks to user bin...
ln -sf $NET_HOME/dotfiles/fishy /cs/home/$USER/usr/bin

# Finish timer
TIME=$(("$(date +%s%3N)" - START))
echo Done in ${TIME}ms!
echo

# Actually leave the dotfiles directory
popd
"$NET_HOME/dotfiles/fish.sh"
