#!/bin/bash
START=$(date +%s%3N)
NET_HOME="/cs/home/$USER/"
HOME="/home/$USER/"

echo Making config directory if not existing...
mkdir -p ~/.config/fish

echo Creating symlinks... 
ln -sf $NET_HOME/dotfiles/fish/config.fish $HOME/.config/fish/config.fish

TIME=$(("$(date +%s%3N)" - START))
echo Done in ${TIME}ms!
sleep 0.5
fish
